// ==UserScript==
// @name        VisualStruct
// @namespace   BL
// @include     *
// @version     1
// @grant       none
// @require     http://code.jquery.com/jquery-1.11.0.min.js
// @require     VS_API.min.js
// @require     VS_Params.min.js
// @require     VS_Predicates.min.js
// @require     VS_Plugin.min.js
// ==/UserScript==

var countSize=0,color="black",colorChanged=!1,background="white",backgroundOrigin,hideImagesValue="no",alreadyRun=!1,ErrorSameColor="Impossible de choisir une couleur de police identique a la couleur de fond",NodeArray=[],root=document.getElementsByTagName("body")[0];function NodeClass(){this.Node=this.Name=""}$(document).ready(function(){backgroundOrigin=$("body").css("background-color");$("img").attr("hide","no");CreateBar();SetupCSS();OverlayHandle();LoadParams();$("#ter__modify").drags()});
function CreateBar(){$("body").append('<button id="ter__modify">Double-cliquez <br/>pour ouvrir <br/>le formulaire</button>');var a;a='<div id="ter__overlay"><div id="ter__form"><div id="ter__Police"><div id="ter__Titre">Police</div><div id="ter__fonts" class="ter__block">Agrandir la police<br/><button id="ter__downFont" class="BtnTaille">--</button><button id="ter__upFont" class="BtnTaille">++</button></div><div id="ter__colors" class="ter__block">Choisir la couleur de fond du site<br/>';a+='<button id="ter__colorBlue">&nbsp;&nbsp;</button><button id="ter__colorBlack">&nbsp;&nbsp;</button><button id="ter__colorGreen">&nbsp;&nbsp;</button><button id="ter__colorWhite">&nbsp;&nbsp;</button><button id="ter__ColorYellow">&nbsp;&nbsp;</button></div><div id="ter__colorFont" class="ter__block">Choisir la couleur d\'\u00e9criture<br />';
a+='<button id="ter__colorFontBlue">AA</button><button id="ter__colorFontBlack">AA</button><button id="ter__colorFontGreen">AA</button><button id="ter__colorFontWhite">AA</button><button id="ter__ColorFontYellow">AA</button></div><br />';a+='Contraste des couleurs  (63% min conseill\u00e9) : <span id="ter__indContrast"></span>';a+='</div><div id="ter__interactivite" class="ter__block"><input type="checkbox" name="ter__alt_only" value="HideImg">Afficher le texte alternatif des images</div><br />';
a+='Afficher uniquement le bloc : <select id="ter__selectNode">';a+="</select><br/>";a+='<div id="ter__choice" class="ter__block"><button id="ter__flush" class="BtnTaille">R\u00e9initialiser</button><button id="ter__cancel" class="BtnTaille">Annuler</button><button id="ter__confirm" class="BtnTaille">Confirmer</button></div></div></div>';$("body").append(a)}
function displayDivOnly(a){$("body").children().hide();var b='<div id="displayOnly">'+NodeArray[a].Node.innerHTML;$("body").append(b);$("body").append('<button id="ter__cancelDisplay" class="BtnTaille">Annuler</button></div>');$("button#ter__cancelDisplay").on("click",function(){refresh();$("#ter__modify").show()});$("button#ter__modify").show();indice=a}function refresh(){location.reload()}
function SetupCSS(){$("#ter__modify").css({"float":"right",position:"fixed",right:"0",top:"10px","text-align":"center",padding:"10px",width:"125px",height:"125px",background:"#fafafa","box-shadow":"2px 2px 8px #aaa",font:"bold 1em Arial","border-radius":"50%",color:"#000"});$("#ter__form").css({width:"50%",height:"auto",top:"25px",left:"25%",opacity:"1",overflow:"visible","z-index":"8030",padding:"0",margin:"0",border:"0",outline:"none","vertical-align":"top",position:"relative",display:"inline-block",
"text-shadow":"none","text-align":"center","border-radius":"10px","background-color":"black",color:"white","font-size":"2em"});$(".ter__block button").css({background:"#000000","-webkit-border-radius":"10","-moz-border-radius":"10","border-radius":"10px","font-family":"Arial",color:"#ffffff","font-size":"30px",padding:"10px20px10px20px",border:"solid#ffffff3px","text-decoration":"none"});$("#ter__Titre").css({"padding-top":"20px"});$("button#ter__colorBlue").css({"background-color":"blue"});$("button#ter__colorBlack").css({"background-color":"black"});
$("button#ter__colorGreen").css({"background-color":"green"});$("button#ter__ColorYellow").css({"background-color":"yellow"});$("button#ter__colorWhite").css({"background-color":"white"});$("button#ter__colorFontBlue").css({"background-color":"blue"});$("button#ter__colorFontBlack").css({"background-color":"black"});$("button#ter__colorFontGreen").css({"background-color":"green"});$("button#ter__ColorFontYellow").css({"background-color":"yellow"});$("button#ter__colorFontWhite").css({"background-color":"white",
color:"white","text-shadow":"-1px 0 black, 0 1px black, 1px 0 black, 0 -1px black"});$("#ter__overlay").css({background:"url('http://sd-1.archive-host.com/membres/up/142586199450897653/fancybox_overlay.png') repeat",width:"auto",height:"auto",display:"block",position:"fixed",bottom:"0",right:"0",top:"0",left:"0",overflow:"hidden","-webkit-border-radius":"5px","-moz-border-radius":"5px","border-radius":"5px"});$(".ter__block").css({"background-color":"transparent",color:"white",display:"inline-block",
"font-family":"Calibri",padding:"10px"});$("#ter__Police").css({display:"block"})}
function OverlayHandle(){$("#ter__overlay").hide();$("#ter__modify").dblclick(function(){alreadyRun||(main(),alreadyRun=!0,DomTree(root,"Discover"),FillList());$("#ter__modify").hide();$("#ter__overlay").fadeIn()});$("button#ter__flush").on("click",function(){FlushParams();alert("Les param\u00e8tres ont \u00e9t\u00e9 r\u00e9initialis\u00e9s avec succ\u00e8s.");refresh()});$("button#ter__cancel").on("click",function(){CancelUpdate();$("#ter__modify").show();$("#ter__overlay").fadeOut()});$("button#ter__confirm").on("click",
function(){hideImages();$("#ter__modify").show();$("#ter__overlay").fadeOut();SaveParams()});$(document).keydown(function(a){27==a.keyCode&&($("#ter__modify").show(),$("#ter__overlay").fadeOut())});$("button.BtnTaille").mouseenter(function(){$(this).css("background","#00ed3f")}).mouseleave(function(){$(this).css("background","000000")});$("button#ter__downFont").on("click",function(){5>parseInt($("*").css("font-size"))||(countSize--,DomTree(root,"--"))});$("button#ter__upFont").on("click",function(){countSize++;
DomTree(root,"++")});$("button#ter__colorBlue").on("click",function(){"blue"==color?alert(ErrorSameColor):($("body").css({"background-color":"blue"}),background="blue",DisplayContrast())});$("button#ter__colorGreen").on("click",function(){"green"==color?alert(ErrorSameColor):($("body").css({"background-color":"green"}),background="green",DisplayContrast())});$("button#ter__colorBlack").on("click",function(){"black"==color?alert(ErrorSameColor):($("body").css({"background-color":"black"}),background=
"black",DisplayContrast())});$("button#ter__ColorYellow").on("click",function(){"yellow"==color?alert(ErrorSameColor):($("body").css({"background-color":"yellow"}),background="yellow",DisplayContrast())});$("button#ter__colorWhite").on("click",function(){"white"==color?alert(ErrorSameColor):($("body").css({"background-color":"white"}),background="white",DisplayContrast())});$("button#ter__colorFontBlue").on("click",function(){"blue"==background?alert(ErrorSameColor):(color="blue",DomTree(root,"blue"),
colorChanged=!0);DisplayContrast()});$("button#ter__colorFontGreen").on("click",function(){"green"==background?alert(ErrorSameColor):(color="green",DomTree(root,"green"),colorChanged=!0);DisplayContrast()});$("button#ter__colorFontBlack").on("click",function(){"black"==background?alert(ErrorSameColor):(color="black",DomTree(root,"black"),colorChanged=!0);DisplayContrast()});$("button#ter__ColorFontYellow").on("click",function(){"yellow"==background?alert(ErrorSameColor):(color="yellow",DomTree(root,
"yellow"),colorChanged=!0);DisplayContrast()});$("button#ter__colorFontWhite").on("click",function(){"white"==background?alert(ErrorSameColor):(color="white",DomTree(root,"white"),colorChanged=!0);DisplayContrast()});$("#ter__selectNode").change(function(){$("#ter__modify").show();$("#ter__overlay").slideUp();displayDivOnly($("#ter__selectNode").val())})}
function DomTree(a,b){WorkToDo(a,b);if(a.hasChildNodes()&&-1==a.id.indexOf("ter__"))for(var c=a.firstChild;c;)1===c.nodeType&&DomTree(c,b),c=c.nextSibling}
function WorkToDo(a,b){if(-1==a.id.indexOf("ter__")&&("++"==b&&($(a).css("font-size",parseInt($(a).css("font-size"))+1+"px"),console.log(countSize)),"--"==b&&($(a).css("font-size",parseInt($(a).css("font-size"))-1+"px"),console.log(countSize)),"black"==b&&$(a).css({color:"black"}),"blue"==b&&$(a).css({color:"blue"}),"white"==b&&$(a).css({color:"white"}),"yellow"==b&&$(a).css({color:"yellow"}),"green"==b&&$(a).css({color:"green"}),"Discover"==b&&"co"==$(a).attr("ter_supertype"))){var c=$(a).attr("ter_semantic");
if("unknown"!=c){var d=new NodeClass;d.Name=c;d.Node=a;NodeArray.push(d)}}}function SaveParams(){localStorage.setItem("Size",countSize);localStorage.setItem("Color",color);localStorage.setItem("Background",background);$('input[name="ter__alt_only"]').is(":checked")?localStorage.setItem("hideImages","yes"):localStorage.setItem("hideImages","no")}
function LoadParams(){var a=null,a=localStorage.getItem("Size");if(null!==a){if(0<a)for(i=0;i<a;i++)DomTree(root,"++"),countSize=a;if(0>a)for(a*=-1,i=0;i<a;i++)DomTree(root,"--"),countSize=-1*a}color=localStorage.getItem("Color");null===color?color="black":DomTree(root,color);DisplayContrast();background=localStorage.getItem("Background");null===background?background="white":$("body").css({"background-color":background});DisplayContrast();hideImagesValue=localStorage.getItem("hideImages");"yes"==
hideImagesValue?($('input[name="ter__alt_only"]').prop("checked",!0),hideImages()):$('input[name="ter__alt_only"]').prop("checked",!1)}function FlushParams(){localStorage.removeItem("Size");localStorage.removeItem("Color");localStorage.removeItem("Background");localStorage.removeItem("hideImages")}
function CancelUpdate(){if(0<countSize)for(i=0;i<countSize+1;i++)DomTree(root,"--"),countSize=0;else if(0>countSize){var a=-1*countSize;console.log(a);for(i=0;i<a+1;i++)DomTree(root,"++"),countSize=0}null!=localStorage.getItem("Color")&&DomTree(root,localStorage.getItem("Color"));localStorage.getItem("Background")?$("body").css({"background-color":localStorage.getItem("Background")}):$("body").css({"background-color":backgroundOrigin});refresh()}
function hideImages(){$('input[name="ter__alt_only"]').is(":checked")?$("img").each(function(){if("no"==$(this).attr("hide")){var a='<span class="ter__alt_text">'+$(this).attr("alt")+"</span>";$(this).attr("hide","yes").hide().after(a)}}):($("img").attr("hide","no").show(),$("span.ter__alt_text").remove())}
(function(a){a.fn.drags=function(b){b=a.extend({handle:"",cursor:"move"},b);return(""===b.handle?this:this.find(b.handle)).css("cursor",b.cursor).on("mousedown",function(c){var d=""===b.handle?a(this).addClass("draggable"):a(this).addClass("active-handle").parent().addClass("draggable"),e=d.css("z-index"),f=d.outerHeight(),g=d.outerWidth(),h=d.offset().top+f-c.pageY,k=d.offset().left+g-c.pageX;d.css("z-index",1E3).parents().on("mousemove",function(b){a(".draggable").offset({top:b.pageY+h-f,left:b.pageX+
k-g}).on("mouseup",function(){a(this).removeClass("draggable").css("z-index",e)})});c.preventDefault()}).on("mouseup",function(){""===b.handle?a(this).removeClass("draggable"):a(this).removeClass("active-handle").parent().removeClass("draggable")})}})(jQuery);function FillList(){for(var a="",b=0;b<NodeArray.length;b++)a+='<option value="'+b+'"> '+NodeArray[b].Name+"</option>";$("#ter__selectNode").append(a)}
function hexToRgb(a){a=a.replace(/^#?([a-f\d])([a-f\d])([a-f\d])$/i,function(a,c,d,e){return c+c+d+d+e+e});return(a=/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(a))?{r:parseInt(a[1],16),g:parseInt(a[2],16),b:parseInt(a[3],16)}:null}function getBritghtness(a,b,c){return(299*red+587*Green+114*Blue)/1E3}
function DisplayContrast(){var a,b;switch(color){case "black":a="#000000";break;case "blue":a="#0000FF";break;case "yellow":a="#FFFF00";break;case "white":a="#FFFFFF";break;case "green":a="#008800"}switch(background){case "black":b="#000000";break;case "blue":b="#0000FF";break;case "yellow":b="#FFFF00";break;case "white":b="#FFFFFF";break;case "green":b="#008800"}a=hexToRgb(a);b=hexToRgb(b);b=maximum(a.r,b.r)-minimum(a.r,b.r)+(maximum(a.g,b.g)-minimum(a.g,b.g))+(maximum(a.b,b.b)-minimum(a.b,b.b));
console.log(b);$("#ter__indContrast").text(Math.floor(100*b/765)+"%");console.log("Ratio (en %) : "+100*b/765);console.log("Ratio suffisant (flat) = 500");console.log("Ratio suffisant (en %) = 63.35%")}function maximum(a,b){return a>=b?a:b}function minimum(a,b){return a>=b?b:a};